'''Generator for the (ordinary) triangle groups or Von Dyck groups.
These are the Fuchsian groups generated by rotations of angles 2pip 2piq 2pir
around the vertices of a hyperbolic triangle whose interior angles are
pi/p pi/q and pi/r respectively.

The hyperbolic case (which is what we're doing here) requires the condition
1/p + 1/q + 1/r < 1.'''

from math import pi, cos, sin, acosh

def trianglesides(p,q,r):
	'''Returns the three sides of the triangle with interior angles pi/p,pi/q,pi/r.'''
	def secondlawofcosines(alpha,beta,gamma):
		'''Returns side opposite to angle gamma via horrible hyperbolic trigonometry.'''
		return acosh((cos(gamma)+cos(alpha)*cos(beta))/(sin(alpha)*sin(beta)))
	alpha,beta,gamma = pi/p, pi/q,pi/r
	return secondlawofcosines(beta, gamma, alpha), secondlawofcosines(gamma, alpha, beta), secondlawofcosines(alpha, beta, gamma)

